# Generated by Django 2.2 on 2022-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Borrower', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowerInfo',
        ),
    ]
