# Generated by Django 2.2 on 2022-04-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrower', '0003_borrowerprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofileinfo',
            name='wallet_addr',
            field=models.CharField(default='NULL', max_length=256),
        ),
    ]
