# Generated by Django 2.2 on 2022-04-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrower', '0005_borrowerprofileinfo_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofileinfo',
            name='address',
            field=models.CharField(default='NULL', max_length=256),
        ),
        migrations.AddField(
            model_name='borrowerprofileinfo',
            name='lat',
            field=models.CharField(default='NULL', max_length=256),
        ),
        migrations.AddField(
            model_name='borrowerprofileinfo',
            name='lon',
            field=models.CharField(default='NULL', max_length=256),
        ),
    ]
