# Generated by Django 2.2 on 2022-04-01 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='NUll', max_length=200)),
                ('last_name', models.CharField(default='NUll', max_length=200)),
                ('username', models.CharField(default='NULL', max_length=200, unique=True)),
                ('contact_no', models.CharField(default='Null', max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
