# Generated by Django 2.2 on 2022-04-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderinfo',
            name='wallet_addr',
            field=models.CharField(default='NULL', max_length=256),
        ),
    ]
