# Generated by Django 2.2 on 2022-04-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lender', '0002_lenderinfo_wallet_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderinfo',
            name='upi_id',
            field=models.CharField(default='NULL', max_length=256),
        ),
    ]
