# Generated by Django 2.2 on 2022-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lender', '0003_lenderinfo_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderinfo',
            name='account_number',
            field=models.CharField(default='NULL', max_length=256),
        ),
    ]
