# Generated by Django 2.2 on 2022-04-04 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactioninfo', to=settings.AUTH_USER_MODEL)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactionuserinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
