# Generated by Django 2.2 on 2022-04-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='lender_id',
            new_name='lender',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='recipient_id',
            new_name='recipient',
        ),
    ]
