# Generated by Django 2.2 on 2022-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_auto_20220404_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
