# Generated by Django 2.2 on 2022-04-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_suspectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
