# Generated by Django 2.2 on 2022-04-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_auto_20220406_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='lon',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
        ),
    ]
