# Generated by Django 2.2 on 2022-04-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_auto_20220406_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectlist',
            name='amount',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
